FROM openresty/openresty:1.25.3.2-3-alpine-apk
RUN mkdir -p /etc/nginx/lua && cat /dev/null > /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
RUN rm -f /usr/local/openresty/nginx/conf/nginx.conf && \
	ln -s /etc/nginx/nginx.conf /usr/local/openresty/nginx/conf/nginx.conf && \
	ln -s /usr/local/openresty/nginx/logs /var/log/nginx  